[build]
  # entra na pasta frontend pra rodar o build
  base = "frontend"

  # nada de generate-env, é só instalar e rodar o build de CSS
  command = "npm install --no-optional && npm run build"

  # como o base é "frontend", "." aqui significa: publicar a própria pasta frontend
  publish = "."

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
