[build]
  base = "frontend"
  publish = "frontend/dist"
  command = "node ../scripts/generate-env.js && npm install --no-optional && npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200